kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  log-format-escaping: "json"
  log-format: '{ "@timestamp": "$time_iso8601", "remote_addr":
      "$remote_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "bytes_sent":
      "$body_bytes_sent", "request_time": "$request_time", "status": "$status",
      "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
      "request_query": "$args", "request_length": "$request_length",
      "duration": "$request_time", "method": "$request_method", "http_referrer":
      "$http_referer", "http_user_agent": "$http_user_agent", "request" : "$request", "http_x_forwarded_for":"$http_x_forwarded_for"}'
#  stream-log-format: '{ "@timestamp": "$time_iso8601", "remote_addr":
#      "$remote_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "bytes_sent":
#      "$bytes_sent", "request_time": "$request_time", "status": "$status",
#      "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
#      "request_query": "$args", "request_length": "$request_length",
#      "duration": "$request_time", "method": "$request_method", "http_referrer":
#      "$http_referer", "http_user_agent": "$http_user_agent"}'      

